import type { StructuredActivitiesLog, ActivityModel } from "../models/activity.model";

// Helper to generate IDs
const uid = () => Math.random().toString(36).substr(2, 9);

export const MOCK_LEDGER_DATA: StructuredActivitiesLog = {
  years: [
    {
      year: 2024,
      totals: {
        distance_meters: 845000, // 845km
        duration_seconds: 288000, // ~80 hours
        elevation_gain_meters: 12400,
        activitiesCount: 72,
      },
      months: [
        {
          month: 4,
          monthName: "April",
          totals: {
            distance_meters: 210000,
            duration_seconds: 72000,
            elevation_gain_meters: 3200,
            activitiesCount: 18,
          },
          weeks: [
            {
              weekNumber: 15,
              startDate: "2024-04-08",
              endDate: "2024-04-14",
              days: [
                {
                  date: "2024-04-08",
                  dayOfWeek: 1,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "intervals",
                    start_time: "2024-04-08T07:00:00Z",
                    distance_meters: 12000,
                    duration_seconds: 3300,
                    elevation_gain_meters: 45,
                    avg_heart_rate: 165,
                    avg_pace_min_per_km: 4.58,
                    rpe: 8,
                    notes: "6x800m track session. Felt strong.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                {
                  date: "2024-04-09",
                  dayOfWeek: 2,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "easy_run",
                    start_time: "2024-04-09T08:15:00Z",
                    distance_meters: 8500,
                    duration_seconds: 2700,
                    elevation_gain_meters: 110,
                    avg_heart_rate: 142,
                    avg_pace_min_per_km: 5.29,
                    rpe: 4,
                    notes: "Easy recovery, HR stayed low.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  },
                },
                { date: "2024-04-10", dayOfWeek: 3, isRestDay: true, activity: null },
                {
                  date: "2024-04-11",
                  dayOfWeek: 4,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "tempo",
                    start_time: "2024-04-11T17:30:00Z",
                    distance_meters: 15000,
                    duration_seconds: 4050,
                    elevation_gain_meters: 80,
                    avg_heart_rate: 158,
                    avg_pace_min_per_km: 4.5,
                    rpe: 7,
                    notes: "Threshold effort. Wind was tough.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                { date: "2024-04-12", dayOfWeek: 5, isRestDay: true, activity: null },
                {
                  date: "2024-04-13",
                  dayOfWeek: 6,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "long_run",
                    start_time: "2024-04-13T08:00:00Z",
                    distance_meters: 28000,
                    duration_seconds: 8400,
                    elevation_gain_meters: 450,
                    avg_heart_rate: 148,
                    avg_pace_min_per_km: 5.0,
                    rpe: 6,
                    notes: "Weekend long run. Nutrition test.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                { date: "2024-04-14", dayOfWeek: 0, isRestDay: true, activity: null },
              ],
              totals: {
                distance_meters: 63500,
                duration_seconds: 18450,
                elevation_gain_meters: 685,
                activitiesCount: 4,
              },
            },
            {
              weekNumber: 15,
              startDate: "2024-04-08",
              endDate: "2024-04-14",
              days: [
                {
                  date: "2024-04-08",
                  dayOfWeek: 1,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "intervals",
                    start_time: "2024-04-08T07:00:00Z",
                    distance_meters: 12000,
                    duration_seconds: 3300,
                    elevation_gain_meters: 45,
                    avg_heart_rate: 165,
                    max_heart_rate: 182,
                    avg_pace_min_per_km: 4.58,
                    rpe: 8,
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                {
                  date: "2024-04-09",
                  dayOfWeek: 2,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "easy_run",
                    start_time: "2024-04-09T08:15:00Z",
                    distance_meters: 8500,
                    duration_seconds: 2700,
                    elevation_gain_meters: 110,
                    avg_heart_rate: 142,
                    max_heart_rate: 158,
                    avg_pace_min_per_km: 5.29,
                    rpe: 4,
                    notes:
                      "Easy recovery, HR stayed low. To match your screenshot exactly, you would place this component underneath the main activity title: technical look seen in fitness apps like Strava or TrainingPeaks.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  },
                },
                { date: "2024-04-10", dayOfWeek: 3, isRestDay: true, activity: null },
                {
                  date: "2024-04-11",
                  dayOfWeek: 4,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "tempo",
                    start_time: "2024-04-11T17:30:00Z",
                    distance_meters: 15000,
                    duration_seconds: 4050,
                    elevation_gain_meters: 80,
                    avg_heart_rate: 158,
                    max_heart_rate: 182,
                    avg_pace_min_per_km: 4.5,
                    rpe: 7,
                    notes: "Threshold effort. Wind was tough.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                { date: "2024-04-12", dayOfWeek: 5, isRestDay: true, activity: null },
                {
                  date: "2024-04-13",
                  dayOfWeek: 6,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "long_run",
                    start_time: "2024-04-13T08:00:00Z",
                    distance_meters: 28000,
                    duration_seconds: 8400,
                    elevation_gain_meters: 450,
                    avg_heart_rate: 148,
                    max_heart_rate: 162,
                    avg_pace_min_per_km: 5.0,
                    rpe: 6,
                    notes: "Weekend long run. Nutrition test.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                { date: "2024-04-14", dayOfWeek: 0, isRestDay: true, activity: null },
              ],
              totals: {
                distance_meters: 63500,
                duration_seconds: 18450,
                elevation_gain_meters: 685,
                activitiesCount: 4,
              },
            },
            {
              weekNumber: 15,
              startDate: "2024-04-08",
              endDate: "2024-04-14",
              days: [
                {
                  date: "2024-04-08",
                  dayOfWeek: 1,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "intervals",
                    start_time: "2024-04-08T07:00:00Z",
                    distance_meters: 12000,
                    duration_seconds: 3300,
                    elevation_gain_meters: 45,
                    avg_heart_rate: 165,
                    max_heart_rate: 182,
                    avg_pace_min_per_km: 4.58,
                    rpe: 8,
                    notes: "6x800m track session. Felt strong.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                {
                  date: "2024-04-09",
                  dayOfWeek: 2,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "strength",
                    workout_type: "easy_run",
                    start_time: "2024-04-09T08:15:00Z",
                    distance_meters: 8500,
                    duration_seconds: 2700,
                    elevation_gain_meters: 110,
                    avg_heart_rate: 142,
                    avg_pace_min_per_km: 5.29,
                    rpe: 4,
                    notes: "Easy recovery, HR stayed low.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  },
                },
                { date: "2024-04-10", dayOfWeek: 3, isRestDay: true, activity: null },
                {
                  date: "2024-04-11",
                  dayOfWeek: 4,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "swim",
                    workout_type: "tempo",
                    start_time: "2024-04-11T17:30:00Z",
                    distance_meters: 15000,
                    duration_seconds: 4050,
                    elevation_gain_meters: 80,
                    avg_heart_rate: 158,
                    avg_pace_min_per_km: 4.5,
                    rpe: 7,
                    notes: "Threshold effort. Wind was tough.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                { date: "2024-04-12", dayOfWeek: 5, isRestDay: true, activity: null },
                {
                  date: "2024-04-13",
                  dayOfWeek: 6,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "trail",
                    workout_type: "long_run",
                    start_time: "2024-04-13T08:00:00Z",
                    distance_meters: 28000,
                    duration_seconds: 8400,
                    elevation_gain_meters: 450,
                    avg_heart_rate: 148,
                    avg_pace_min_per_km: 5.0,
                    rpe: 6,
                    notes: "Weekend long run. Nutrition test.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  } as ActivityModel,
                },
                { date: "2024-04-14", dayOfWeek: 0, isRestDay: true, activity: null },
              ],
              totals: {
                distance_meters: 63500,
                duration_seconds: 18450,
                elevation_gain_meters: 685,
                activitiesCount: 4,
              },
            },
            // Note: In a real app, you'd have more week entries here
          ],
        },
        {
          month: 3,
          monthName: "March",
          totals: {
            distance_meters: 245000,
            duration_seconds: 86400,
            elevation_gain_meters: 4100,
            activitiesCount: 22,
          },
          weeks: [
            {
              weekNumber: 12,
              startDate: "2024-03-18",
              endDate: "2024-03-24",
              days: [
                {
                  date: "2024-03-18",
                  dayOfWeek: 1,
                  isRestDay: false,
                  activity: {
                    id: uid(),
                    user_id: "u1",
                    activity_type: "run",
                    workout_type: "tempo",
                    start_time: "2024-03-18T07:00:00Z",
                    distance_meters: 10000,
                    duration_seconds: 3200,
                    avg_heart_rate: 138,
                    avg_pace_min_per_km: 5.33,
                    rpe: 3,
                    notes: "Z2 aerobic base.",
                    created_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                  },
                },
                // ... repeated days
              ],
              totals: {
                distance_meters: 75000,
                duration_seconds: 21600,
                elevation_gain_meters: 1200,
                activitiesCount: 6,
              },
            },
          ],
        },
        {
          month: 2,
          monthName: "February",
          totals: {
            distance_meters: 180000,
            duration_seconds: 61200,
            elevation_gain_meters: 2800,
            activitiesCount: 16,
          },
          weeks: [], // Data would populate here
        },
        {
          month: 1,
          monthName: "January",
          totals: {
            distance_meters: 210000,
            duration_seconds: 68400,
            elevation_gain_meters: 2300,
            activitiesCount: 16,
          },
          weeks: [], // Data would populate here
        },
      ],
    },
  ],
  totals: {
    distance_meters: 845000,
    duration_seconds: 288000,
    elevation_gain_meters: 12400,
    activitiesCount: 72,
  },
};
